name: CrackCityRaids
main: com.abevriens.CrackCityRaids
version: '1.0.0'
load: POSTWORLD
description: The official CrackCity raids plugin, made for crackcity.online by Abe Vriens
author: IemandDieAbeHeet
website: abevriens.com
api-version: 1.17

commands:
  factions:
    description: All faction commands.
    usage: /<command> <action> <arguments>
    permission: crackcity.factions
    aliases: [f]