name: CockCityRaids
main: com.abevriens.CockCityRaids
version: '1.0.0'
load: POSTWORLD
description: The official CockCity raids plugin, made for cockcity.online by Abe Vriens
author: IemandDieAbeHeet
website: abevriens.com
api-version: 1.17